// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa2WiZEIfbnvoCK8SXTqJQ6B4Qw7T5X1M',
    appId: '1:317661900103:web:786b2d3489c9432d4eb062',
    messagingSenderId: '317661900103',
    projectId: 'af-main',
    authDomain: 'af-main.firebaseapp.com',
    storageBucket: 'af-main.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPVOcAfPyZufwzByiXtZMwd0bpqi1O0R0',
    appId: '1:317661900103:android:f10a2415d4f874c14eb062',
    messagingSenderId: '317661900103',
    projectId: 'af-main',
    storageBucket: 'af-main.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQ_oYHK8SXQB9DN5Z65Ob8dMxVbMoTJdo',
    appId: '1:317661900103:ios:c69b45444874d4764eb062',
    messagingSenderId: '317661900103',
    projectId: 'af-main',
    storageBucket: 'af-main.firebasestorage.app',
    iosBundleId: 'com.example.af',
  );
}
